### ISSUE TITLE
 How to get number of chirps per frame?

### ISSUE THREAD

**Issue by kangk906** [azinke/mmwave-repack#1]
Hello, Thanks for your repository. I have a quick question: Should I take into account the variable 'numLoops' when determining the value of 'NC'?

**Comment by azinke** [comment]
Hi @kangk906 !
`nc` is directly the number of chirp loops per frame. It's indeed not that clear in the readme. I'll fix that. Thank you!

**Comment by kangk906** [comment]
Thank you for your assistance. I have a follow-up inquiry. I've noticed that the trihedral corner reflector is quite expensive. I was wondering if you made the trihedral corner reflector yourself or if you purchased it from Amazon?
